const formstyle = {
    card: {
        padding: 2,
        width: 450,
        height: 380,
        position: 'absolute',
        top: '40%',
        left: 0,
        right: 0,
        margin: 'auto',
        opacity: 0.85
    },
    content: {
        textAlign: 'center',
        position: 'absolute',
        left: 0,
        right: 0,
        margin: 'auto',
    },
    textField: {
        width: 400,
    },
    button1: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 150,
        left: -146,
        right: 0,
        margin: 'auto',
    },
    button2: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 150,
        left: 0,
        right: 0,
        margin: 'auto',
    },
    button3: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 150,
        left: 146,
        right: 0,
        margin: 'auto',
    },
    button4: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 200,
        left: -146,
        right: 0,
        margin: 'auto',
    },
    button5: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 200,
        left: 0,
        right: 0,
        margin: 'auto',
    },
    button6: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 200,
        left: 146,
        right: 0,
        margin: 'auto',
    },
    button7: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 250,
        left: -146,
        right: 0,
        margin: 'auto',
    },
    button8: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 250,
        left: 0,
        right: 0,
        margin: 'auto',
    },
    button9: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 250,
        left: 146,
        right: 0,
        margin: 'auto',
    },
    button0: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 300,
        left: 0,
        right: 0,
        margin: 'auto',
    },
    buttonPlus: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 300,
        left: -146,
        right: 0,
        margin: 'auto',
    },
    buttonDel: {
        width: 40,
        height: 40,
        position: 'absolute',
        top: 300,
        left: 146,
        right: 0,
        margin: 'auto',
    }
};

export default formstyle;